name: jmitch
favicon: null
layout_spectrum: 0.8426864065695554
typography_spectrum: 0.6707563688978553
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7794998676981777
  lightness: 0.48369103972800076
  saturation: 0.11549318651668727
  rhythmicContrast: 0.2107199290767312
purpose: []
